steps:
# Instance Template Creation
- name: gcr.io/cloud-builders/gcloud
  id: create-instance-template
  args:
      - compute
      - instance
      - templates
      - create
      - cloudbuild-priya-template
      - --project=searce-playground-v1
      - --source-instance=sheetal-test-vm
      - --source-instance-zone=asia-south1-a
